### ISSUE TITLE
Sorry，I have a question

### ISSUE THREAD

**Issue by liujinwakayakulie** [freddi-kit/dcgan-exp#1]
Sorry,i can't find other way to talk with you. I  don't have twitter account.
Now,I want to add my pass in the pipeline of passes.i watch the video https://www.youtube.com/watch?v=QBXcCTfwyZ8
In 28:12S ,I don't know what happened. I don't know how to `Swiftc XXX.swift` with my local swift compile project.
Can you give me your email? I'm so sorry to talk with you by this way .

**Comment by freddi-kit** [comment]
@liujinwakayakulie hi, I answer it. In 28:12, This is listing what pass is called by using `-Xllvm -sil-print-pass-name`. 

You can use like `swiftc test.swift -Xllvm -sil-print-pass-name`.

**Comment by freddi-kit** [comment]
And, if you want to use your build local swift compiler, you have to find where your built one is and call it directly. In movie, this looks like I'm calling by normal swiftc command, but I'm writing some script to use my local build one (by finding path of my local build).

**Comment by freddi-kit** [comment]
The location of your local build swift compiler is `{your-build-folder-root}/Xcode-DebugAssert/swift-macosx-x86_64/Debug/bin/` if you build it by generating Xcode project. The second folder name(`Xcode-DebugAssert`) is changed if you build with other way like ninja.

**Comment by freddi-kit** [comment]
And if you build swift compiler with recent one, you have to make `{your-build-folder-root}/Xcode-DebugAssert/swift-macosx-x86_64/Debug/bin/swift-frontend`'s symbolic link and name it as `swiftc`, to call it as `swiftc` command.

**Comment by freddi-kit** [comment]
Please don't say sorry, and my email address in my resume, plz check it :)
https://gist.github.com/freddi-kit/0ba99d07e6a84dcca5496c2e3d88e4ce#contacts

**Comment by liujinwakayakulie** [comment]
thank you ! I will try it,thanks
